### ISSUE TITLE
[FEATURE] CarbonAware SDK Update due to WattTime API Update

### ISSUE THREAD

**Issue by lwluc** [envite-consulting/camunda-carbon-reductor#111]
**Is your feature request related to a problem? Please describe.**
WattTime has released a new API Version, see https://docs.watttime.org/

**Describe the solution you'd like**
Using the new WattTime v3 API everything works as expected.

**Additional context**
Carbon Aware SDK needed and support for the new API Version:
- https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/532
- https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/538

**Comment by CRoberto1926** [comment]
Carbon Aware SDK v1.5.0 was released 3 days ago, and they are dropping support for WattTime v2 API. See Release Notes: https://github.com/Green-Software-Foundation/carbon-aware-sdk/releases/tag/v1.5.0
